name: Build and deploy ASP.Net Core app to Azure Web App - avansict2229380

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read # This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      # Specify the correct path to your project directory if not in the root
      #correct the path here
      - name: Build with dotnet
        run: |
          cd API/API/API.csproj     
          dotnet build --configuration Release
        
    #correct the path here
      - name: dotnet publish
        run: |
          cd  API/API/API.csproj
          dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # This is required for requesting the JWT
      contents: read # This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_0A126A11D2B14C9AAF07EC70FBCAD71C }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_ED3A9974EE1946ED91A5AFECC77B86F7 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_FEBE210B9B3F4E72BE7CBA54DC40B784 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'avansict2229380'
          slot-name: 'Production'
          package: .
