name: Build and Deploy ASP.NET Core app to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  ARTIFACT_NAME: WebApi
  DOTNET_CORE_VERSION: 9.0.x
  PUBLISH_DIRECTORY: ./publish

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_CORE_VERSION }}

      - name: Restore
        run: dotnet restore ${{ secrets.WEBAPI_PROJECT_NAME }}

      - name: Build
        run: dotnet build ${{ secrets.WEBAPI_PROJECT_NAME }} --no-restore

      - name: Test
        run: dotnet test ${{ secrets.WEBAPI_PROJECT_NAME }} --no-build

      - name: Publish
        run: dotnet publish ${{ secrets.WEBAPI_PROJECT_NAME }} -c Release -o ${{ env.PUBLISH_DIRECTORY }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ${{ env.PUBLISH_DIRECTORY }}

  deploy:
    runs-on: windows-latest
    needs: build
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{ env.PUBLISH_DIRECTORY }}
